# Generated by Django 4.2.2 on 2023-06-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Interest',
        ),
        migrations.AddField(
            model_name='user',
            name='interests',
            field=models.CharField(choices=[('Food', 'Food'), ('Movies', 'Movies'), ('Travel', 'Travel'), ('Cycling', 'Cycling')], max_length=20, null=True),
        ),
    ]
