# Generated by Django 4.2.2 on 2023-09-11 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_connectionrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='connectionrequest',
            options={'verbose_name_plural': 'Connection Requests'},
        ),
        migrations.AddField(
            model_name='connectionrequest',
            name='sent_by',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='connectionrequest',
            name='sent_to',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
