# Generated by Django 4.2.2 on 2023-09-11 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_connectionrequest_sent_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='interests',
        ),
        migrations.DeleteModel(
            name='Interest',
        ),
    ]
